### ISSUE TITLE
Error with Pictures of higher resolution

### ISSUE THREAD

**Issue by FJ16Ja** [mpizenberg/rgbd-tracking-evaluation#2]
Hello,

I installed DVO on my windows System and it works fine with the given Testdata (Freiburg1).
When I tried to implement my own Dataset of pictures with resolution 848x480, dense_tracking throws an error in line 350 (ref_dx =ref.intensity_dx * intrinsics.fx();) "Critical error detected c0000374".

Maybe someone knows, what to do.
Thank you for yout help

**Comment by mpizenberg** [comment]
Hi @FJ16Ja . This is an issue which has to do with DVO directly. That repo (rgbd-tracking-evaluation) is just for evaluation. I've just verified now and the DVO included here (as a submodule) is a fork I did of the original DVO to make it easily compile on recent linux. That fork is available here: https://github.com/mpizenberg/dvo. In there I explained that I didn't do any algorithm change except re-orthogonalization of the rotation matrices needed with the update of Sophus. But as you can see in the diff (https://github.com/tum-vision/dvo/compare/fuerte...mpizenberg:no-ros) I didn't touch the part of DVO's code that's dealing with dense tracking and causing your error.

So your best chance at getting an answer to your question is to open an issue directly on the original DVO's repository: https://github.com/tum-vision/dvo

Cheers,
Matthieu
